[2025-04-21T09:46:53.348-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T09:46:53.355-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T12:41:43.868120+00:00 [queued]>
[2025-04-21T09:46:53.360-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T12:41:43.868120+00:00 [queued]>
[2025-04-21T09:46:53.360-0300] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-04-21T09:46:53.374-0300] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dw_metastore> on 2025-04-21 12:41:43.868120+00:00
[2025-04-21T09:46:53.376-0300] {standard_task_runner.py:72} INFO - Started process 40736 to run task
[2025-04-21T09:46:53.378-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dw_metastore_pipeline', 'run_dw_metastore', 'manual__2025-04-21T12:41:43.868120+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/q.py', '--cfg-path', '/tmp/tmp04c1cbeb']
[2025-04-21T09:46:53.379-0300] {standard_task_runner.py:105} INFO - Job 75: Subtask run_dw_metastore
[2025-04-21T09:46:53.405-0300] {task_command.py:467} INFO - Running <TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T12:41:43.868120+00:00 [running]> on host DESKTOP-1GIT60U.
[2025-04-21T09:46:53.446-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dw_metastore_pipeline' AIRFLOW_CTX_TASK_ID='run_dw_metastore' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T12:41:43.868120+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T12:41:43.868120+00:00'
[2025-04-21T09:46:53.446-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-21T09:46:53.456-0300] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-21T09:46:53.456-0300] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "\n#!/bin/bash\nexport SPARK_HOME=/opt/spark\nexport SPARK_LOCAL_IP=127.0.0.1  # ou o IP local do seu host, se necessário\n\n# Criar diretórios com permissões corretas\nmkdir -p /home/lenovo/airflow/spark-warehouse\nmkdir -p /home/lenovo/airflow/metastore_db\nchmod -R 777 /home/lenovo/airflow/spark-warehouse\nchmod -R 777 /home/lenovo/airflow/metastore_db\n\n# Executar o script PySpark com Hive Metastore\n$SPARK_HOME/bin/spark-submit     --master local[*]     --driver-memory 4g     --conf spark.sql.warehouse.dir=/home/lenovo/airflow/spark-warehouse     --conf spark.sql.catalogImplementation=hive     --conf hive.metastore.uris=''     /home/lenovo/airflow/jobs/jobs_functions/dw_sparkmetastore.py"]
[2025-04-21T09:46:53.462-0300] {subprocess.py:99} INFO - Output:
[2025-04-21T09:46:55.000-0300] {subprocess.py:106} INFO - Warning: Ignoring non-Spark config property: hive.metastore.uris
[2025-04-21T09:46:55.875-0300] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-21T09:46:55.876-0300] {subprocess.py:106} INFO -   File "/home/lenovo/airflow/jobs/jobs_functions/dw_sparkmetastore.py", line 9, in <module>
[2025-04-21T09:46:55.876-0300] {subprocess.py:106} INFO -     from jobs.log_utils.logging_function import configurar_logger, notificar_falha
[2025-04-21T09:46:55.876-0300] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'jobs'
[2025-04-21T09:46:55.926-0300] {subprocess.py:106} INFO - 25/04/21 09:46:55 INFO ShutdownHookManager: Shutdown hook called
[2025-04-21T09:46:55.929-0300] {subprocess.py:106} INFO - 25/04/21 09:46:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-cc52a7fc-be36-4c6d-81af-9413bc891b51
[2025-04-21T09:46:55.969-0300] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-21T09:46:55.975-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T09:46:55.977-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dw_metastore_pipeline, task_id=run_dw_metastore, run_id=manual__2025-04-21T12:41:43.868120+00:00, execution_date=20250421T124143, start_date=20250421T124653, end_date=20250421T124655
[2025-04-21T09:46:55.989-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-21T09:46:55.990-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task run_dw_metastore (Bash command failed. The command returned a non-zero exit code 1.; 40736)
Traceback (most recent call last):
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T09:46:55.998-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T09:46:56.006-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T09:46:56.007-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
